site_name: VHDL Development
use_directory_urls: false

markdown_extensions:
  - admonition
  - codehilite

nav:
  - Home: index.md
  - VHDL By Application: VHDL/VHDL By Application.md
  - About: about.md

theme:
  name: material
  feature:
    tabs: true
  palette:
    primary: blue grey

docs_dir: markdown
site_dir: docs
